### ISSUE TITLE
bibliografia

### ISSUE THREAD

**Issue by Luisangelriverosbautista** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-Luisangelriverosbautista#1]
[Infografía .pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-Luisangelriverosbautista/files/14577042/Infografia.pdf)

**Comment by GerardoNR** [comment]
17
le falto información mas detallada, he imágenes

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
